# permissions for end users to view fabricnetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fabricnetwork-viewer-role
rules:
- apiGroups:
  - hyperledger.org
  resources:
  - fabricnetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hyperledger.org
  resources:
  - fabricnetworks/status
  verbs:
  - get
