
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hyperledger.org
  resources:
  - fabricnetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hyperledger.org
  resources:
  - fabricnetworks/finalizers
  verbs:
  - update
- apiGroups:
  - hyperledger.org
  resources:
  - fabricnetworks/status
  verbs:
  - get
  - patch
  - update
